# Generated by Django 3.2.5 on 2021-10-18 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211017_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image3',
        ),
    ]
