# Generated by Django 3.2.5 on 2021-10-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails'),
        ),
    ]
